### PR TITLE
`sys.getfilesystemencoding()` return value on Windows

### PR DESCRIPTION
**Pull request by techtonik**
Need that for https://github.com/Olga-Yakovleva/RHVoice/pull/34

### CODE REVIEW

**Comment by techtonik** [comment]
On Ubuntu 20.04 it outputs `UTF-8`
```
❯ python2 -c "import sys; print('sys.getfilesystemencoding() - ' + sys.getfilesystemencoding())"
sys.getfilesystemencoding() - UTF-8
```

**Comment by techtonik** [comment]
@abitrolly CI doesn't seem to be working. The README.md points to https://ci.appveyor.com/project/abitrolly/windows

**Comment by abitrolly** [comment]
@techtonik I've created team using this instruction https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization and sent you invite. Should be working now - https://ci.appveyor.com/project/yakshaveinc/windows

**Comment by abitrolly** [comment]
Oops. Looks like there is no `python2` on Windows https://ci.appveyor.com/project/yakshaveinc/windows/builds/33754001

**Comment by abitrolly** [comment]
@techtonik added you the privileges. Now you can push to `master` directly.

**Comment by techtonik** [comment]
Awesome. =) I forgot that Windows uses `py -2` launcher instead of `python2`. Will fix right now.

**Pull request merged**
